name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: arichtman
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Brisbane
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://www.richtman.com.au/atom.xml
          plugin_stars: yes
          plugin_stars_limit: 4
